§1. 前提条件

In [1]:
import numpy as np

§2. スライシング（部分抽出）

In [2]:
v = np.arange(10,15)
v

array([10, 11, 12, 13, 14])

In [3]:
v[2:4]

array([12, 13])

In [4]:
v[:3]

array([10, 11, 12])

In [5]:
v[3:]

array([13, 14])

In [6]:
v[:-1]

array([10, 11, 12, 13])

In [7]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [8]:
u = a[0,:]
u

array([1, 2])

In [9]:
u = a[:,1]
u

array([2, 4])

In [10]:
ii = np.array([2,3])
v[ii]

array([12, 13])

In [11]:
w = np.array([False,False,False,True,True])
v[w]

array([13, 14])

§3. ブロードキャスティング（全要素に対する演算の反映）

In [12]:
a*2

array([[2, 4],
       [6, 8]])

In [13]:
np.exp(a)

array([[  2.71828183,   7.3890561 ],
       [ 20.08553692,  54.59815003]])

In [14]:
v<13

array([ True,  True,  True, False, False], dtype=bool)

In [15]:
v[v<13]

array([10, 11, 12])