§1. 前提条件

In [2]:
import numpy as np

In [3]:
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [4]:
b

array([[ 6,  7,  8],
       [ 9, 10, 11]])

§2. 横方向の結合

In [5]:
np.c_[a,b]

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

§3. 縦方向の結合

In [6]:
np.r_[a,b]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

§4. 1次元配列の結合

In [7]:
c = np.arange(3)
d = np.arange(3,6)
c

array([0, 1, 2])

In [8]:
d

array([3, 4, 5])

In [9]:
np.c_[c,d]

array([[0, 3],
       [1, 4],
       [2, 5]])

In [10]:
np.r_[c,d]

array([0, 1, 2, 3, 4, 5])