§1. 前提条件

In [2]:
import numpy as np

§2. 行列の生成と形状変更

In [5]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [6]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
c = b.reshape(2,5)
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

§3. 行列の演算

In [9]:
a = np.arange(4).reshape(2,2)
a

array([[0, 1],
       [2, 3]])

In [10]:
b = np.arange(3,7).reshape(2,2)
b

array([[3, 4],
       [5, 6]])

In [11]:
a+b

array([[3, 5],
       [7, 9]])

In [12]:
a.T

array([[0, 2],
       [1, 3]])

In [13]:
a.T+b

array([[3, 6],
       [6, 9]])

In [14]:
a-b

array([[-3, -3],
       [-3, -3]])

In [15]:
np.dot(a,b)

array([[ 5,  6],
       [21, 26]])

In [16]:
v = np.array([10,20])
np.dot(a,v)

array([20, 80])

In [17]:
np.dot(v,a)

array([40, 70])